MODULE = openwsn
# 
# INCLUDES += -I$(OPENWSN_ROOT)/openapps/uecho \
#       -I$(CURDIR)/openapps/opencoap \
# 			-I$(CURDIR)/openapps/uinject \
# 			-I$(CURDIR)/openapps/userialbridge \
# 			-I$(CURDIR)/openapps/rtt \

include $(RIOTBASE)/Makefile.base
